### ISSUE TITLE
Week 1 - Basic Types 

### ISSUE THREAD

**Issue by apjama** [app-ren-teec/python-beginners#1]
1. Read this: http://scipy-lectures.org/intro/language/first_steps.html
2. Watch this: https://youtu.be/5Y-MghiDmQ4. 
3. Read: http://scipy-lectures.org/intro/language/basic_types.html. 
4. answer the following questions and post your repl link below: https://repl.it/@apjama1/UnequaledDevotedMegahertz#main.py

If you're stuck on anything, post here and ask the rest of the team.

**Comment by mohamedabdisalam** [comment]
Hey folks, hope everyone is good!

I've shared the link to my attempt at addressing the questions - https://repl.it/join/srpgctwx-mohamedabdisala

If anybody has a better way to do some of the things give me a shout (or if the link above doesn't work)!

**Comment by apjama** [comment]
@mohamedabdisalam is it definitely public bro? i can't seem to see it.

**Comment by mohamedabdisalam** [comment]
I'm trying to figure this out right now - it's blank when I go back to it so I suspect it may not have saved

**Comment by mohamedabdisalam** [comment]
@apjama it should all be there now - the issue was that I had typed straight into the console

**Comment by Kamal9-tech** [comment]
Hey guys, here's my attempt at answering the questions. Got a bit confused
in some areas and I doubt I got everything right but I'll share my link too
so I could get feedback and corrections where needed.
https://repl.it/join/gvmdpnwe-kamalduran

**Comment by malab1** [comment]
For some reason I can't seem to open up ipython (i've downloaded anaconda). Only these options show 
![Screenshot 2021-01-13 at 11 47 22](https://user-images.githubusercontent.com/77211593/104448560-3e618a80-5595-11eb-804e-a324c15c764a.png)

**Comment by Zhagi** [comment]
Hi guys, I've linked my attempt down below. 

Although it didn't feature in the questions I couldn't get my head around Slicing a[start:stop:step]
When you have a = "hello, world!"
a = "hello, world!"
a[2:10:2]  # Syntax: a[start:stop:step]
'l o o' 
I understand the first L is '2' and it stops at '10' (does this skip the comma?) with increments of '2' 
so I understand it is 'l o o' but why is the l in 'world' not counted or the exclamation mark?

If anyone can give an explanation that'd be really kind :)

Zubayda

https://repl.it/@ZubaydaHagi/UnequaledDevotedMegahertz#main.py

**Comment by zxsaleem** [comment]
Hi Guys,
Heres my attempt on answering the questions below. (Got a tad bit confused, shared the the link on the talk section thinking it would automatically post on here).

https://repl.it/@zxsaleem/UnequaledDevotedMegahertz-2#main.py

**Comment by MohamudMussa** [comment]
salaam people,

here is my attempt - https://repl.it/@MohamudMussa/UnequaledDevotedMegahertz

kind regards
Mussa

**Comment by Mustinelli** [comment]
Salaam everyone,

My attempt on answering the questions:
https://repl.it/@Mustinelli/UnequaledDevotedMegahertz
[https://www.gravatar.com/avatar/2b51c5054c6a69247554e2191080dad8?d=https://repl.it/public/images/evalbot/evalbot_21.png&s=256]<https://repl.it/@Mustinelli/UnequaledDevotedMegahertz>
UnequaledDevotedMegahertz<https://repl.it/@Mustinelli/UnequaledDevotedMegahertz>
A Python repl by Mustinelli
repl.it





________________________________

**Comment by apjama** [comment]
Hey @mohamedabdisalam. Thanks for this. Just a point of clarification regarding your answer: 
`print('A tuple is immutable and is separated by commas')`

A list and a tuple are basically the same thing. They're both separated by commas. ['yes, 'hello', 1] vs ('yes', 'hello', 1). The second one, a tuple cannot be changed.

**Comment by apjama** [comment]
hey @Kamal9-tech. Nice work. I just had a few notes to give re your work.

1) you used del colour (0) to remove the first item. That certainly works. You could have also used `pop`. Here's a quick link on other things you could have done. https://www.csestack.org/difference-between-remove-del-pop-python-list/ 

2) Your answer on whats the difference between lists and dictionaries. You said `A list is an ordered sequence of objects whereas dictionaries are unordered sets.`. I think a better way of thinking about it is that dictionaries, you can look up stuff using their keys. 
dictionary ---> {key: value, key2: value}. List ---> [12, 3, 4, 6, 7, "value"]. 

3) variables in python are snake cased. so we use underscores. You used inputStr = "Kamal". kamal is more pythonic.

**Comment by apjama** [comment]
@zxsaleem I think you accidentally deleted @Zhagi's comment. Nice work btw. I just had one comment on printing your name. 

Basically if I write "some name". That's just a string. To make Python print it out in the shell, I need to run it use the function the print function: `print(my_name)`. 

Also I noticed that there's a space between the functions you're using and the arguments. So for `print()` and `type()` you had a space. you don't need to put a space there. `type(something)` to the type of something.

**Comment by apjama** [comment]
@MohamudMussa looks good! @Mustinelli, nice work! I just had a comment regarding your use of `.remove()`. 

In Python, you've got three ways of removing an element from a list. `.pop` and `del` use an index. So you say, hey, remove the thing that's at position 0, or 1, etc etc. .remove() you say, hey, get rid of the first thing that looks like this. So .remove(4) says, get rid of the first four u see. I posted the link above to an article that explains the difference between the three things.

**Comment by Zhagi** [comment]
Here is mine again :) 

https://repl.it/@ZubaydaHagi/UnequaledDevotedMegahertz#main.py

**Comment by zxsaleem** [comment]
> @zxsaleem I think you accidentally deleted @Zhagi's comment. Nice work btw. I just had one comment on printing your name.
> 
> Basically if I write "some name". That's just a string. To make Python print it out in the shell, I need to run it use the function the print function: `print(my_name)`.
> 
> Also I noticed that there's a space between the functions you're using and the arguments. So for `print()` and `type()` you had a space. you don't need to put a space there. `type(something)` to the type of something.

@Zhagi I am so sorry, it was an accident. @apjama Thank you very much for your feedback.

**Comment by SheikhAli97** [comment]
Salaams Everyone,
Here is my attempt at the task.

https://repl.it/@SheikhAli97/UnequaledDevotedMegahertz-2#main.py

thanks!

**Comment by apjama** [comment]
Nice work @SheikhAli97! Just one comment on style. `sortedColors = sorted(colors);`. `sortedColors` in python would be` `sorted_colors`. Python prefers snake case for variable names and function names.

**Comment by malab1** [comment]
Hi guys, here's my attempt https://repl.it/@sumz2345/UnequaledDevotedMegahertz#main.py

**Comment by apjama** [comment]
Nice one @malab1. When you were adding two strings together. You could have also used f strings. Here's a quick post about them: https://zetcode.com/python/fstring/. They're super powerful and can be so helpful when you want to do more complex stuff with string. 

Well done everyone btw. I'm closing this ticket now :)
